on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: 🔨 Build Project
        run: |
          npm install
          npm run production

      - name: install composer
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: "lowest"

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_APP_NAME: Laravel
          envkey_APP_KEY: base64:GkQc8HDlfsxjaxR9mdrYfi2FgwkGHn+WSCoC3Ohh+zc=
          envkey_DB_CONNECTION: mysql
          envkey_DB_HOST: mysql79.hostland.ru
          envkey_DB_PORT: 3306
          envkey_DB_DATABASE: host1848044
          envkey_DB_USERNAME: host1848044
          envkey_DB_PASSWORD: ESizyKvs3T
          file_name: .env
          fail_on_empty: false

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ftp79.hostland.ru
          username: host1848044
          password: ${{ secrets.password }}
          server-dir: host1848044.hostland.pro/htdocs/www/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
